Fixed -r option so that all appropriate deps are removed. Updated err messages and where they are printed. Added -h option for displaying help infomation.

diff --git a/sbopkg-dep2sqf b/sbopkg-dep2sqf
--- a/sbopkg-dep2sqf
+++ b/sbopkg-dep2sqf
@@ -7,6 +7,7 @@ function print_usage {
     echo "Usage: `basename $0` [options] <dep-file>"
     echo "Options:"
     echo "  -c          Check if packages are already installed from other sources; only active with option -o"
+    echo "  -h          Show this information"
     echo "  -o          Enable optional packages"
     echo "  -p          Print the dependency tree (does not generate sqf file)"
     echo "  -r          Generates sqf file to remove a package and dependencies"
@@ -82,7 +83,7 @@ function parse_dep_file {
     local metapkg=$?
 
     if (( $metapkg == 0 )); then
-	if (( $CHECK_IS_INST == 1 )); then
+	if (( $CHECK_IS_INST_EXT == 1 )); then
 	    check_is_inst $topdep 0 # check only non-SBo packages
 	    (( $? == 1 )) && return
 	fi
@@ -90,11 +91,18 @@ function parse_dep_file {
 	echo "$topdep $(get_buildopts $topdep)" >> $dep
     fi
 
+    if [[ -z $(grep -x $topdep $PKGLIST) ]]; then
+	echo -en "${COLOR_FAIL}[FAIL]${COLOR_END} " > /dev/stderr
+	echo "$topdep not in $PKGLIST" > /dev/stderr
+	exit 1
+    fi
+
     if [[ ! -f $topdep ]]; then
+	echo -en "${COLOR_WARN}[WARN]${COLOR_END} "
 	echo "$topdep dependency file not found--assuming no dependencies"
 	return
     fi
-
+    
     local in_block=0
     while read l
     do
@@ -194,15 +202,16 @@ function gen_sqf_rm_file {
 
     sqf="rm-${sqf}"
     rm -f $sqf
-    
+
     while read p
     do
-	p=$(echo $p | cut -d' ' -f1)
+	p=$(echo $p | cut -d'|' -f1)
+
 
 	local remove=0
 
 	# Check if the pkg is installed
-	check_is_inst $p 1 &> /dev/null # Check only SBo packages
+	check_is_inst $p 1 1> /dev/null # Check only SBo packages
 	if (( $? == 1 )); then # Is installed
 	    remove=1
 	    # Loop through the package list seeing if this packages is needed
@@ -210,21 +219,23 @@ function gen_sqf_rm_file {
 	    do
 		[[ $p == $pl ]] && continue
 		# Check if it is a package in the queue file
-		local t=$(grep $pl .tmp)
-		[[ ! -z $t ]] && continue
+		local test=$(grep $pl .tmp)
+		[[ ! -z $test ]] && continue
 
-		t=$(grep -x $p $pl)
-		if [[ ! -z $t ]]; then
-		    check_is_inst $pl 1 &> /dev/null # Check only SBo packages
+		test=$(grep -x $p $pl)
+		if [[ ! -z $test ]]; then
+		    check_is_inst $pl 1 1> /dev/null # Check only SBo packages
 		    # Other package needs this one
 		    if (( $? == 1 )); then
-			echo -e "${COLOR_FAIL}[KEEP]${COLOR_END} $p (needed by $pl)"
+			echo -e "${COLOR_FAIL}[KEEP]${COLOR_END} " > /dev/stderr
+			echo "$p (needed at least by $pl)" > /dev/stderr
 			remove=0
 			break
 		    fi
 		fi
 	    done<$PKGLIST
 	fi
+
 
 	if (( remove == 1 )); then
 	    echo -e "${COLOR_OK}[RM]${COLOR_END} $p"
@@ -238,7 +249,7 @@ function gen_sqf_rm_file {
     if [[ -f $sqf ]]; then
 	echo -e "${COLOR_OK}[OK]${COLOR_END} $sqf generated"
     else
-	echo -e "${COLOR_FAIL}[FAIL]${COLOR_END} $sqf not generated"
+	echo -e "${COLOR_FAIL}[FAIL]${COLOR_END} $sqf not generated" > /dev/stderr
     fi
 }
 
@@ -278,7 +289,7 @@ function check_is_entry {
 ################################################################################
 function check_is_inst {
     local pkg=$1
-    local include=$2
+    local sbo_only=$2
 
     for f in /var/log/packages/${pkg}*
     do 
@@ -293,15 +304,15 @@ function check_is_inst {
 
 	if [[ $name == $pkg ]]; then
 
-	    [[ -z $include ]] && return 1
+	    [[ -z $sbo_only ]] && return 1
 
-	    if [[ ! $include && $ext != *"_SBo"  ]]; then
+	    if [[ (( $sbo_only == 0 )) && $ext != *"_SBo"  ]]; then
 		echo -ne "${COLOR_INFO}[INFO]${COLOR_END} "
 		echo "external installation of $pkg found: $pkg_other"
 		return 1
 	    fi
 
-	    if [[ $include && $ext == *"_SBo" ]]; then
+	    if [[ (( $sbo_only == 1 )) && $ext == *"_SBo" ]]; then
 		echo -ne "${COLOR_INFO}[INFO]${COLOR_END} "
 		echo "installation of $pkg found: $pkg_other"
 		return 1
@@ -371,7 +382,7 @@ ACTION_GENSQF_RM=3
 DEP_TREE_LVL=0
 
 USE_OPTPKGS=0
-CHECK_IS_INST=0
+CHECK_IS_INST_EXT=0
 # Default action
 ACTION=$ACTION_GENSQF
 ARCH=$(uname -m)
@@ -380,8 +391,12 @@ ARCH=$(uname -m)
 while (( $# > 0 )); do
     case $1 in
 	"-c")
-	    CHECK_IS_INST=1
+	    CHECK_IS_INST_EXT=1
 	    shift 1
+	    ;;
+	"-h")
+	    print_usage
+	    exit 0
 	    ;;
 	"-o")
 	    USE_OPTPKGS=1
@@ -416,9 +431,9 @@ if (( $ACTION == $ACTION_PRINT )); then
     print_dep_tree $TOPDEP
 elif (( $ACTION == $ACTION_GENSQF_RM )); then
     # Enable external installed checking
-    CHECK_IS_INST=1
-    parse_dep_file $TOPDEP $DEP
-    gen_sqf_file $DEP $SQF &> /dev/null
+    CHECK_IS_INST_EXT=1
+    parse_dep_file $TOPDEP $DEP 1> /dev/null
+    gen_sqf_file $DEP $SQF 1> /dev/null
     gen_sqf_rm_file $DEP $SQF
 else
     parse_dep_file $TOPDEP $DEP
