Changed dep files to be separated into required and optional dependencies. The script dep2sqf can now generate a combine dep file based on whether the optional deps are desired.

diff --git a/deps/dep2sqf b/deps/dep2sqf
--- a/deps/dep2sqf
+++ b/deps/dep2sqf
@@ -1,19 +1,135 @@
 #!/bin/bash
 
-DEP="$1"
+function print_usage {
+    echo "Usage: `basename $0` [options] <dep-file>"
+    echo "Options:"
+    echo "  -o          Enable optional packages"
+}
+
+function parse_dep_file {
+ 
+   local topdep=$1
+   local dep=$2
+
+   echo $topdep >> $dep
+
+   if [[ ! -f $topdep ]]; then
+       echo "$topdep dependency file not found--assuming no dependencies"
+       return
+   fi
+
+    while read l
+    do 
+	if [[ $l == "REQUIRED:" || -z $l ]]; then
+	    /bin/true
+	elif [[ $l == "OPTIONAL:" ]]; then
+	    (( USE_OPTPKGS == 0 )) && break
+	    /bin/true
+	else
+	    parse_dep_file $l $dep
+	fi
+    done<$topdep
+}
+
+function pad_blanks {
+    for (( i=0; i<$1; i++ ))
+    do
+	echo -n "  "
+    done
+}
+
+function print_dep_tree {
+ 
+   local topdep=$1
+
+   pad_blanks $DEP_TREE_LVL
+   echo $topdep
+
+   DEP_TREE_LVL=$(( DEP_TREE_LVL + 2 ))
+
+   if [[ ! -f $topdep ]]; then
+       echo "$topdep dependency file not found--assuming no dependencies"
+       return
+   fi
+
+    while read l
+    do 
+	if [[ $l == "REQUIRED:" || -z $l ]]; then
+	    pad_blanks $DEP_TREE_LVL
+	    echo $l
+	elif [[ $l == "OPTIONAL:" ]]; then
+	    (( USE_OPTPKGS == 0 )) && break
+	    echo $l
+	else
+	    print_dep_tree $l
+	fi
+    done<$topdep
+
+    DEP_TREE_LVL=$(( DEP_TREE_LVL - 2 ))
+}
+
+
+function gen_sqf_file {
+
+    local dep=$1
+    local sqf=$2
+
+    tac $dep > .$dep
+    rm -f $sqf && touch $sqf
+
+    while read l
+    do
+	p=$(echo $l)
+	p_test=$(grep -w $p $sqf)
+	if [[ -z $p_test ]]; then
+	    echo $p >> $sqf
+	fi
+	
+    done<.$dep
+    rm -f .$dep
+}
+
+# Set defaults
+ACTION_PRINT=1
+ACTION_GENSQF=2
+DEP_TREE_LVL=0
+
+USE_OPTPKGS=0
+ACTION=$ACTION_GENSQF
+
+# Run through the options
+while (( $# > 0 )); do
+    case $1 in
+	"-o")
+	    USE_OPTPKGS=1
+	    shift 1
+	    ;;
+	"-p")
+	    ACTION=$ACTION_PRINT
+	    shift 1
+	    ;;
+	*)
+	    break
+    esac
+done
+
+if (( $# != 1 )); then
+    print_usage
+    exit 1
+fi
+
+TOPDEP="$1"
+DEP="dep"
 SQF="$1.sqf"
 
-tac $DEP > .$DEP
-rm -f $SQF && touch $SQF 
+rm -f $DEP
+rm -f $SQF
 
-while read l
-do
-    p=$(echo $l)
-    p_test=$(grep -w $p $SQF)
-    if [[ -z $p_test ]]; then
-	echo $p >> $SQF
-    fi
-    
-done<.$DEP
+if (( $ACTION == $ACTION_PRINT )); then
+    print_dep_tree $TOPDEP
+else
+    parse_dep_file $TOPDEP $DEP
+    gen_sqf_file $DEP $SQF
+fi
 
-rm -f .$DEP
+rm -f $DEP
